server.port=8080
spring.application.name=climalert-service
spring.threads.virtual.enabled=true

weather.api.key=5763297f7c7541a3983213503260607
weather.api.city=CABA

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=agrynszpan@frba.utn.edu.ar
spring.mail.password=dftyrisbokvpuiwx

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000